# -*- coding: utf-8 -*-
"""
Regenerate the-ledger.html (the panel source vault.py builds from).

the-ledger.html is NOT precious and is NOT shipped with the skill. It is an
intermediate. It went stale inside the skill once and cost us two panels, so it
is now always regenerated from one of two durable sources:

  python3 restore.py                     from the-vault.html (the last build,
                                         e.g. staged from the desktop artifact
                                         `the-ledger`). Zero database reads.

  python3 restore.py --from-json         from ledger_panels.json, pulled out of
                                         Supabase. The recovery path when no
                                         desktop is connected or the artifact is
                                         gone. Shape:
                                         [{"slug","palette_css","panel_html"}, ...]
                                         select slug, palette_css, panel_html
                                         from film_ledger_panels;
"""
import re, io, os, sys, json

_here = os.path.dirname(os.path.abspath(__file__))
BASE = os.environ.get("VAULT_DIR") or (
    _here if os.path.exists(os.path.join(_here, "the-vault.html"))
    or os.path.exists(os.path.join(_here, "ledger_panels.json"))
    else os.path.dirname(_here))

OUT = os.path.join(BASE, "the-ledger.html")


def from_json():
    src = os.path.join(BASE, "ledger_panels.json")
    rows = json.load(io.open(src, encoding="utf-8"))
    pals = [r["palette_css"].strip() for r in rows]
    panels = [r["panel_html"].strip() for r in rows]
    return pals, panels


def from_vault():
    src = os.path.join(BASE, "the-vault.html")
    doc = io.open(src, encoding="utf-8").read()

    m = re.search(r'/\* ledger palettes: start \*/(.*?)/\* ledger palettes: end \*/',
                  doc, re.S)
    if not m:
        raise SystemExit(
            "No palette markers in the-vault.html. That build predates the "
            "markers. Use --from-json instead.")
    pal_lines = [l for l in m.group(1).strip().split("\n") if l.strip()]
    by_slug = {}
    for line in pal_lines:
        slug = re.match(r'\.([a-z0-9-]+)', line).group(1)
        by_slug.setdefault(slug, []).append(line)

    # ledger panels carry data-set="ledger"; strip every injected attribute back
    # off so the result is byte-identical to what was hand authored.
    raw = re.findall(
        r'<section class="panel ([a-z0-9-]+)" data-set="ledger"[^>]*>.*?</section>',
        doc, re.S)
    panels = []
    for chunk in re.findall(
            r'<section class="panel [a-z0-9-]+" data-set="ledger"[^>]*>.*?</section>',
            doc, re.S):
        slug = re.match(r'<section class="panel ([a-z0-9-]+)"', chunk).group(1)
        chunk = re.sub(r'^<section class="panel %s"[^>]*>' % slug,
                       '<section class="panel %s">' % slug, chunk, count=1)
        # undo the one build-time copy edit vault.py makes
        chunk = chunk.replace("the Ledger's only perfect score",
                              "the board's only perfect score")
        panels.append(chunk)
    if not panels:
        raise SystemExit("Found no ledger panels in the-vault.html.")
    # emit palettes in panel order so this path is byte-identical to --from-json
    order = [re.match(r'<section class="panel ([a-z0-9-]+)"', c).group(1) for c in panels]
    pals = ["\n".join(by_slug[s]) for s in order if s in by_slug]
    return pals, panels


def main():
    if "--from-json" in sys.argv:
        pals, panels = from_json()
        how = "ledger_panels.json"
    else:
        pals, panels = from_vault()
        how = "the-vault.html"

    # canonical order regardless of source: sort panels (and their palettes)
    # by slug so both restore paths emit identical files.
    import re as _re
    def _slug(x):
        return _re.search(r'\.([a-z0-9-]+)|class="panel ([a-z0-9-]+)"', x).group(0)
    paired = sorted(zip(pals, panels),
                    key=lambda t: _re.match(r'<section class="panel ([a-z0-9-]+)">', t[1]).group(1))
    pals = [a for a, _ in paired]
    panels = [b for _, b in paired]

    # vault.py reads exactly two things out of this file: the palette block
    # (delimited by the historical comment) and the panel sections.
    doc = (u"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n"
           u"<title>The Ledger, panel source</title>\n"
           u"<!-- GENERATED by restore.py from %s. Do not treat as precious.\n"
           u"     Source of truth is film_ledger_panels in Supabase. -->\n<style>\n"
           u"/* the fourteen palettes */\n%s\n\n</style>\n</head>\n<body>\n\n%s\n\n"
           u"</body>\n</html>\n" % (how, "\n".join(pals), "\n\n".join(panels)))
    io.open(OUT, "w", encoding="utf-8").write(doc)
    print("restored %s from %s: %d panels, %d palette lines"
          % (OUT, how, len(panels), len(pals)))


main()
